# Branches that trigger a build on commit
trigger:
- master
- feature/*

# Branches that trigger builds on PR
pr:
- master
- feature/*

jobs:

- job: Format
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 8
    matrix:
      format:
        _repo: "https://github.com/dotnet/format"
        _repoName: "dotnet/format"
        _sha: "b6db94c361b1ecd0558fc7429335ec01133773ed"
      roslyn:
        _repo: "https://github.com/dotnet/roslyn"
        _repoName: "dotnet/roslyn"
        _sha: "665dc224dcfefb66dce215ca0204363172b611ad"
      cli:
        _repo: "https://github.com/dotnet/cli"
        _repoName: "dotnet/cli"
        _sha: "8d0f2a593ec98ccc1ef2141452d7dccadc34ac40"
      project-system:
        _repo: "https://github.com/dotnet/project-system"
        _repoName: "dotnet/project-system"
        _sha: "80580ad27c5544f00f4abb9db930e698ce305285"
      msbuild:
        _repo: "https://github.com/Microsoft/msbuild"
        _repoName: "Microsoft/msbuild"
        _sha: "d54d2e0180b99b7773f0fef2cdb03168f134d9aa"
      Blazor:
        _repo: "https://github.com/aspnet/Blazor"
        _repoName: "aspnet/Blazor"
        _sha: "3addb6169afcae1b5c6a64de4a7cd02bd270ffed"
      EntityFrameworkCore:
        _repo: "https://github.com/aspnet/EntityFrameworkCore"
        _repoName: "aspnet/EntityFrameworkCore"
        _sha: "090f385ffe4f2cd1a3e6b794523bdf574862c298"
      EntityFramework6:
        _repo: "https://github.com/aspnet/EntityFramework6"
        _repoName: "aspnet/EntityFramework6"
        _sha: "936befcd88a4b58be6f35038248cd5337aca4967"
  timeoutInMinutes: 20
  steps:
    - script: eng\integration-test.cmd -repo '$(_repo)' -sha '$(_sha)' -testPath '$(Build.SourcesDirectory)\temp'
      displayName: Run dotnet-format on $(_repoName)
