# Branches that trigger a build on commit
trigger:
- master
- feature/*

# Branches that trigger builds on PR
pr:
- master
- feature/*

jobs:

- job: Format
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    maxParallel: 8
    matrix:
      format:
        _repo: "https://github.com/dotnet/format"
        _repoName: "dotnet/format"
        _sha: "4ff73616469a2aaa5ff07d11b7f6951eca83d76e"
      roslyn:
        _repo: "https://github.com/dotnet/roslyn"
        _repoName: "dotnet/roslyn"
        _sha: "1bd191ea896b19e3b06a152f815f3a998e87049a"
      cli:
        _repo: "https://github.com/dotnet/cli"
        _repoName: "dotnet/cli"
        _sha: "45f1c5f7f3275ff483c804e7c90bf61731a83e97"
      project-system:
        _repo: "https://github.com/dotnet/project-system"
        _repoName: "dotnet/project-system"
        _sha: "fc3b12e47adaad6e4813dc600acf190156fecc24"
      msbuild:
        _repo: "https://github.com/Microsoft/msbuild"
        _repoName: "Microsoft/msbuild"
        _sha: "e92633a735b0e23e2cbf818d02ba89dd7a426f89"
      Blazor:
        _repo: "https://github.com/aspnet/Blazor"
        _repoName: "aspnet/Blazor"
        _sha: "7eeab316fa122b69a9bd777c93dcc78bc6a68905"
      EntityFrameworkCore:
        _repo: "https://github.com/aspnet/EntityFrameworkCore"
        _repoName: "aspnet/EntityFrameworkCore"
        _sha: "94f5bdf081f9a774f5d7f01bfa279bac26dab303"
      EntityFramework6:
        _repo: "https://github.com/aspnet/EntityFramework6"
        _repoName: "aspnet/EntityFramework6"
        _sha: "9099ad2f6e5936ecdf549f88394b5a59fa75c869"
  timeoutInMinutes: 20
  steps:
    - script: eng\integration-test.cmd -repo '$(_repo)' -sha '$(_sha)' -testPath '$(Build.SourcesDirectory)\temp'
      displayName: Run dotnet-format on $(_repoName)
